# Generated by Django 6.0.2 on 2026-03-04 09:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mrn', models.CharField(blank=True, max_length=30, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('Unknown', 'Unknown')], max_length=10)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='patient_photos/')),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('pincode', models.CharField(blank=True, max_length=10)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=200)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20)),
                ('emergency_contact_relation', models.CharField(blank=True, max_length=100)),
                ('allergies', models.TextField(blank=True, default='None')),
                ('chronic_conditions', models.TextField(blank=True)),
                ('current_medications', models.TextField(blank=True)),
                ('past_surgical_history', models.TextField(blank=True)),
                ('family_history', models.TextField(blank=True)),
                ('insurance_provider', models.CharField(blank=True, max_length=200)),
                ('insurance_policy_number', models.CharField(blank=True, max_length=100)),
                ('insurance_expiry', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Discharged', 'Discharged')], default='Active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.TimeField()),
                ('doctor', models.CharField(choices=[('Dr. Kavita Sharma', 'Dr. Kavita Sharma'), ('Dr. Sanjay Mehta', 'Dr. Sanjay Mehta'), ('Dr. Ananya Rao', 'Dr. Ananya Rao'), ('Dr. Rajesh Patel', 'Dr. Rajesh Patel'), ('Dr. Meera Nair', 'Dr. Meera Nair'), ('Dr. Arun Verma', 'Dr. Arun Verma'), ('Dr. Priya Reddy', 'Dr. Priya Reddy'), ('Dr. Suresh Kumar', 'Dr. Suresh Kumar')], max_length=200)),
                ('department', models.CharField(choices=[('Cardiology', 'Cardiology'), ('Pulmonology', 'Pulmonology'), ('Neurology', 'Neurology'), ('Orthopedics', 'Orthopedics'), ('General Medicine', 'General Medicine'), ('Pediatrics', 'Pediatrics'), ('Gynecology', 'Gynecology'), ('Dermatology', 'Dermatology'), ('ENT', 'ENT'), ('Ophthalmology', 'Ophthalmology'), ('Oncology', 'Oncology'), ('Urology', 'Urology'), ('Psychiatry', 'Psychiatry'), ('Endocrinology', 'Endocrinology'), ('Gastroenterology', 'Gastroenterology'), ('Nephrology', 'Nephrology'), ('Rheumatology', 'Rheumatology'), ('Emergency', 'Emergency')], max_length=100)),
                ('appointment_type', models.CharField(choices=[('New Consultation', 'New Consultation'), ('Follow-up', 'Follow-up'), ('Emergency', 'Emergency'), ('Procedure', 'Procedure'), ('Lab Review', 'Lab Review')], default='New Consultation', max_length=50)),
                ('duration_minutes', models.CharField(choices=[('15', '15 min'), ('20', '20 min'), ('30', '30 min'), ('45', '45 min'), ('60', '60 min'), ('90', '90 min')], default='30', max_length=10)),
                ('reason', models.TextField()),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Normal', 'Normal'), ('High', 'High'), ('Urgent', 'Urgent')], default='Normal', max_length=20)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('No-Show', 'No-Show')], default='Pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='patients.patient')),
            ],
            options={
                'ordering': ['appointment_date', 'appointment_time'],
            },
        ),
        migrations.CreateModel(
            name='VisitRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField(default=django.utils.timezone.now)),
                ('visit_time', models.TimeField()),
                ('doctor', models.CharField(choices=[('Dr. Kavita Sharma', 'Dr. Kavita Sharma'), ('Dr. Sanjay Mehta', 'Dr. Sanjay Mehta'), ('Dr. Ananya Rao', 'Dr. Ananya Rao'), ('Dr. Rajesh Patel', 'Dr. Rajesh Patel'), ('Dr. Meera Nair', 'Dr. Meera Nair'), ('Dr. Arun Verma', 'Dr. Arun Verma'), ('Dr. Priya Reddy', 'Dr. Priya Reddy'), ('Dr. Suresh Kumar', 'Dr. Suresh Kumar')], max_length=200)),
                ('department', models.CharField(choices=[('Cardiology', 'Cardiology'), ('Pulmonology', 'Pulmonology'), ('Neurology', 'Neurology'), ('Orthopedics', 'Orthopedics'), ('General Medicine', 'General Medicine'), ('Pediatrics', 'Pediatrics'), ('Gynecology', 'Gynecology'), ('Dermatology', 'Dermatology'), ('ENT', 'ENT'), ('Ophthalmology', 'Ophthalmology'), ('Oncology', 'Oncology'), ('Urology', 'Urology'), ('Psychiatry', 'Psychiatry'), ('Endocrinology', 'Endocrinology'), ('Gastroenterology', 'Gastroenterology'), ('Nephrology', 'Nephrology'), ('Rheumatology', 'Rheumatology'), ('Emergency', 'Emergency')], max_length=100)),
                ('visit_type', models.CharField(choices=[('Regular', 'Regular'), ('Follow-up', 'Follow-up'), ('Emergency', 'Emergency'), ('Routine Check-up', 'Routine Check-up'), ('Pre-operative', 'Pre-operative'), ('Post-operative', 'Post-operative')], default='Regular', max_length=50)),
                ('blood_pressure', models.CharField(blank=True, max_length=20)),
                ('pulse_rate', models.CharField(blank=True, max_length=20)),
                ('temperature', models.CharField(blank=True, max_length=20)),
                ('spo2', models.CharField(blank=True, max_length=10)),
                ('weight', models.CharField(blank=True, max_length=20)),
                ('height', models.CharField(blank=True, max_length=20)),
                ('bmi', models.CharField(blank=True, max_length=20)),
                ('respiratory_rate', models.CharField(blank=True, max_length=20)),
                ('chief_complaint', models.TextField()),
                ('history_of_illness', models.TextField(blank=True)),
                ('physical_examination', models.TextField(blank=True)),
                ('diagnosis', models.TextField()),
                ('treatment_plan', models.TextField(blank=True)),
                ('investigations_ordered', models.TextField(blank=True)),
                ('follow_up_instructions', models.TextField(blank=True)),
                ('additional_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Ongoing', 'Ongoing'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Completed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='patients.patient')),
            ],
            options={
                'ordering': ['-visit_date', '-visit_time'],
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_name', models.CharField(max_length=200)),
                ('dosage', models.CharField(max_length=100)),
                ('frequency', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
                ('instructions', models.TextField(blank=True)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='patients.visitrecord')),
            ],
        ),
    ]
